version: '3.8'
name: 'pmanager'
services:
    server:
        container_name: pmanager_server
        build: .
        depends_on:
            # Loading database first :)
            - postgres
        ports:
            - "8080:8080"
        environment:
            - EXTERNAL_PORT=8080
            - PGUSER=root
            - PGPASSWORD=root
            - PGDATABASE=root
            - PGHOST=pmanager_db
            - TOKEN_SECRET=xWmso9Os78GXhkruYB2FMWQPglostosEkCeyMxoWBo4d109RAdhG8pvdiBdJDls
        volumes:
            - ./:/usr/src/app/

    postgres:
        container_name: pmanager_db
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=root
        ports:
            - "5432:5432"
        volumes:
            - pmanager_data:/var/lib/postgresql/data

volumes:
    pmanager_data: {}
